# Generated by Django 4.0.8 on 2022-10-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart_wagons', '0002_alter_mailing_list_id_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing_list_admin',
            name='email',
            field=models.EmailField(db_column='email', max_length=254),
        ),
    ]
