# Generated by Django 4.0.8 on 2022-10-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart_wagons', '0004_alter_mailing_list_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing_list',
            name='name',
            field=models.CharField(db_column='name', max_length=50, null=True),
        ),
    ]
