# Generated by Django 4.0.8 on 2022-10-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart_wagons', '0007_mailing_list_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing_list',
            name='id_client',
            field=models.IntegerField(db_column='id_client', null=True),
        ),
    ]
