# Generated by Django 4.0.8 on 2022-10-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart_wagons', '0008_alter_mailing_list_id_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.IntegerField(db_column='UNIT', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=3)),
            ],
            options={
                'db_table': 'UNIT',
                'managed': False,
            },
        ),
    ]
